### ISSUE TITLE
IDEA - check dependencies within script?

### ISSUE THREAD

**Issue by AtomicRobotMan0101** [weebney/webcamize#4]
Mint Cinnamon 21.2, 6.4.x kernel -> https://termbin.com/4lizh

Thought to add, as a tiny thing, to autodetect that all packages are present and if missing, throw warnings... and/or install them?

I'm going to try this with a few mobiles on RasPi's..... see how it goes.

**Comment by weebney** [comment]
There's already a dependency check included in the script—is there a specific dependency you had in mind that isn't checked?

**Comment by AtomicRobotMan0101** [comment]
I'm no expert at loopbacks, so it was new to me...

gphoto2, ffmpeg, v4l2loopback-dkms, v4l2loopback-utils so far.

All installed now, but still working out how to get these stupid Xiaomi phones to play nice....

(I enjoyed reading this: https://wiki.archlinux.org/title/V4l2loopback  Yours is a very neato project)
