### ISSUE TITLE
Known Issues (READ BEFORE SUBMITTING)

### ISSUE THREAD

**Issue by weebney** [weebney/webcamize#6]
## "Movie capture error..." / "Movie capture finished (0 frames)" / "*** Error (-1: 'Unspecified error') ***"

If your output looks something like:
```console
$ webcamize
...
[FATAL] gphoto2: ...
ERROR: Movie capture error... Exiting.
Movie capture finished (0 frames)
*** Error (-1: 'Unspecified error') ***
```

This almost always means your device is unsupported (and almost always because of a bad or incomplete [PTP](https://en.wikipedia.org/wiki/Picture_Transfer_Protocol) implementation). Complain to the manufacturer!

Consult the [supported devices list](https://github.com/weebney/webcamize/blob/master/assets/supported.md)—if your device is on there, feel free to open a new issue; otherwise, please do not!

## "Possibly missing v4l2loopback module"

Some people may see this every time they run webcamize; it's not always the main issue. If you *don't* usually see it, though, it's probably the main issue. If your output looks like this below, there is a number of steps you can take to fix the problem.

```console
$ webcamize
[WARN] Possibly missing v4l2loopback module
...
[WARN] Pipeline exited with non-0 status (1)
...
```

1. Ensure you have `v4l2loopback` installed. Re-install it if necessary.
2. Double check that you can run `modinfo` without `sudo`
3. Reboot—kernel updates will prevent the module from working until your system is rebooted.

## "ioctl(VIDIOC_G_FMT): Invalid argument" / "Could not write header (incorrect codec parameters ?): Invalid argument"

If your output looks something like:

```console
$ webcamize
...
[WARN] Pipeline exited with non-0 status (1)
[FATAL] ffmpeg: ...
...
[video4linux2,v4l2 @ 0x561ce7fba380] ioctl(VIDIOC_G_FMT): Invalid argument
[out#0/video4linux2,v4l2 @ 0x561ce7fc0e00] Could not write header (incorrect codec parameters ?): Invalid argument
[vost#0:0/rawvideo @ 0x561ce7fbc4c0] Error initializing output stream:
```

This usually means something is wrong with your v4l2loopback module. To start diagnosing the problem, run the command below which will attempt to unload the module:

```console
$ sudo modprobe -r v4l2loopback
```

If this command returns something like `modprobe: FATAL: Module v4l2loopback is in use.`, reboot your system. This is an extremely common issue with v4l2loopback where it gets stuck "in use," and unfortunately rebooting is the only consistent way to fix it.

**Comment by micsthepick** [comment]
https://github.com/cowtoolz/webcamize/blob/master/doc/supported.md - wrong url

presumably because it changed :)

**Comment by cowtoolz** [comment]
Good catch @micsthepick
